name: CI-dev

on: [push, pull_request]

jobs:
  continuous-integration:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: mydb
        options: >-
          --health-cmd="pg_isready -U postgres -d mydb"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci
        
      - name: Wait for Postgres to be ready
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do
            echo "Waiting for Postgres..."
            sleep 2
          done

      - name: Run Prisma migrations
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
        run: npm run migration:up

      - name: Start API server in background
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
        run: ts-node src/server.ts

      - name: Wait for API to be ready
        run: npx wait-on http://localhost:3333/health

      - name: Run integration tests
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/mydb
        run: npx jest --runInBand --detectOpenHandles --forceExit

